---
title: "R y Python"
author: "Pol Buisan"
date: "30/11/2020"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Reticulate

Librería que sirve para compartir R y Python

```{r}
library(reticulate)
use_python("/Users/polbu/anaconda3/python")
#py_install("nombre del paquete a instalar")
#sirve para usar python

os<- import("os")
os$listdir(".")

```
```{r}
source_python("suma.py")
suma(3,4)
```

```{r}
np<- import("numpy", convert=FALSE)
x<- np$array(c(1:4))
sum<- x$cumsum()

print(sum)

py_to_r(sum) #para convertir de python a r
```

## Ayuda

```{r}
help(py_to_r)
py_help(os$chdir)

```

# Arrays

```{r}
a <- np_array(c(1:10), order="C")
a
```

```{r}
datos <-iris
head(datos)
datos_py <- r_to_py(datos)
```

# para pasar la info de r a python


```{r}
library(reticulate)
py_install("pandas")
```
```{python}
import numpy as np
import pandas as pd
r.datos_py .head()


```

```{r}
library(Matrix)
N <-6
set.seed(123)
sparse_mat <- sparseMatrix(
  i=sample(N,N,replace=F),
  j=sample(N,N,replace=F),
  x = runif(N),
  dims=c(N,N) #dimensión de la matriz
)
sparse_mat



```

